# Server Configuration
server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always

spring:
  output:
    ansi:
      enabled: always

  datasource:
    url: jdbc:mysql://localhost:3306/TaskFlow?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true

  liquibase:
    change-log: classpath:./db/changelog-master.xml